import type { RunParams } from '@src/models/workflow';
// This file is generated by the migration script.
// It contains the business logic for the node.

export class NodeHandler {
  /**
   * The core execution logic of the node.
   */
  public async run({ input  }: RunParams) {
        const a = input.a ?? 0;
        const b = input.b ?? 0;
        return { result: a - b }
    }
}
