import type { RunParams } from '@src/models/workflow';
// This file is generated by the migration script.
// It contains the business logic for the node.

export class NodeHandler {
  /**
   * The core execution logic of the node.
   */
  public async run({ input  }: RunParams) {
        // The 'input' object will contain all connected input ports, including dynamic ones.
        // We sum all values in the input object.
        const sum = Object.values(input).reduce((acc: number, val: any) => acc + (Number(val) || 0), 0);
        return { result: sum }
    }
}