import type { RunParams } from '@src/models/workflow';
// This file is generated by the migration script.
// It contains the business logic for the node.

export class NodeHandler {
  /**
   * The core execution logic of the node.
   */
  public async run({ input, params  }: RunParams) {
        const valA = Number(input.a ?? 0);
        const valB = Number(input.b !== undefined ? input.b : params.b);
        return { result: valA >= valB }
    }
}
