import type { RunParams } from '@src/models/workflow';
// This file is generated by the migration script.
// It contains the business logic for the node.

export class NodeHandler {
  /**
   * The core execution logic of the node.
   */
  public async run({ params  }: RunParams) {
        console.log(`[DEBUG] Constant node received params:`, params);
        const { dataType, value } = params;
        let parsedValue: any = params.value;
        try {
            if (params.dataType === 'number') {
                parsedValue = Number(params.value);
            } else if (params.dataType === 'boolean') {
                parsedValue = params.value === 'true' || params.value === '1';
            }
        } catch (error) {
            console.error('Error parsing constant value:', error);
        }
        console.log(`[DEBUG] Constant node returning value: ${parsedValue}`);
        return { value: parsedValue };
    }
}
