import type { RunParams } from '@src/models/workflow';
// This file is generated by the migration script.
// It contains the business logic for the node.

export class NodeHandler {
  /**
   * The core execution logic of the node.
   */
  public async run({ input, params  }: RunParams) {
        const inputArray = input.array_in || [];
        const processedArray = inputArray.map((item: any) => `${item.value}${params.suffix}`);
        return { array_out: processedArray };
    }
}
