<template>
  <Sidebar>
    <div class="node-palette">
      <div
        v-for="def in nodeDefinitions"
        :key="def.type"
        class="palette-node"
        :draggable="true"
        @dragstart="onDragStart($event, def)"
      >
        {{ def.label }}
      </div>
    </div>
  </Sidebar>
  <div class="controls">
    <button @click="saveWorkflow">Save</button>
    <button @click="runWorkflow">Run</button>
  </div>
  <VueFlow
    :nodes="nodes"
    :edges="edges"
    class="main-vueflow"
    @dragover="onDragOver"
    @drop="onDrop"
  >
    <Background />

    <template #node-basenode="basenodeProps">
      <basenode v-bind="basenodeProps" />
    </template>
  </VueFlow>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import type { Node, Edge } from '@vue-flow/core'
import { VueFlow, useVueFlow } from '@vue-flow/core'
import { Background } from '@vue-flow/background'
import { NodeDefinitionsService, NodeDefinition, WorkflowsService } from '@/api'

import '@vue-flow/core/dist/style.css'
import '@vue-flow/core/dist/theme-default.css'

import basenode from '@/node/BaseNode.vue'
import { stringToColor } from './utils/color'

const { onConnect, addEdges, project, addNodes } = useVueFlow()

onConnect((connection) => {
  if (!connection.sourceHandle) {
    console.warn('Connection ignored: source handle is missing.', connection)
    return
  }
  const portName = connection.sourceHandle.replace(/^out-/, '')
  const color = stringToColor(portName).hsl
  const newEdge = {
    ...connection,
    style: {
      stroke: color,
      strokeWidth: 2.5,
    },
    animated: true,
  }
  addEdges(newEdge)
})

const nodes = ref<Node[]>([])
const edges = ref<Edge[]>([])

import Sidebar from './components/Sidebar.vue';

const nodeDefinitions = ref<NodeDefinition[]>([]);

onMounted(async () => {
  try {
    const definitions = await NodeDefinitionsService.getApiNodeDefinitions();
    nodeDefinitions.value = definitions;
  } catch (error) {
    console.error('Failed to fetch node definitions:', error);
  }
});

function onDragStart(event: DragEvent, definition: NodeDefinition) {
  if (event.dataTransfer) {
    event.dataTransfer.setData('application/json', JSON.stringify(definition));
    event.dataTransfer.effectAllowed = 'copy';
  }
}

function onDragOver(event: DragEvent) {
  event.preventDefault();
  if (event.dataTransfer) {
    event.dataTransfer.dropEffect = 'copy';
  }
}

let id = 0;
function getId() {
  return `dndnode_${id++}`;
}

function onDrop(event: DragEvent) {
  const definition = JSON.parse(event.dataTransfer?.getData('application/json') || '{}');
  const { x, y } = project({ x: event.clientX, y: event.clientY });

  const newNode = {
    id: getId(),
    type: 'basenode',
    position: { x, y },
    data: {
      label: definition.label,
      input: definition.ports.filter((p: any) => p.direction === 'in' && p.type === 'data').map((p: any) => ({ name: p.name, data: p.defaultValue })),
      output: definition.ports.filter((p: any) => p.direction === 'out' && p.type === 'data').map((p: any) => ({ name: p.name, data: null })),
    },
  };
  addNodes([newNode]);
}

async function saveWorkflow() {
  try {
    // This is a placeholder for saving a workflow.
    // In a real app, you would likely have a workflow ID.
    // Here we'll just save a new workflow every time.
    const workflow = {
      id: '', // id will be generated by the backend
      name: 'My Workflow',
      graph: {
        nodes: nodes.value,
        edges: edges.value,
      },
    };
    await WorkflowsService.postApiWorkflowsAdd(workflow);
    alert('Workflow saved!');
  } catch (error) {
    console.error('Failed to save workflow:', error);
    alert('Failed to save workflow.');
  }
}

async function runWorkflow() {
  alert('Run functionality is not yet implemented.');
  // Placeholder for run logic. You would typically need a workflow ID to run.
}

</script>

<style scoped>
.main-vueflow {
  background-color: #FAFAFA;
}
.node-palette {
  padding: 10px;
}
.palette-node {
  border: 1px solid #ccc;
  padding: 10px;
  margin-bottom: 10px;
  border-radius: 5px;
  cursor: grab;
}
.controls {
  position: absolute;
  top: 10px;
  right: 10px;
  z-index: 10;
}
</style>
