// This file is generated by the migration script.
import type { RunParams } from '@src/models/workflow';

export class NodeHandler {
  /**
   * The core execution logic of the node.
   */
  public async run({}: RunParams) {
    // This node's logic is handled by the engine or is a placeholder.
    return {};
  }
}
